name: presensi_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.11.0
  http: ^1.2.2
  geocoding: ^3.0.0
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  url_launcher: ^6.1.7
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.2
  flutter_map: ^7.0.2
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  # google_ml_kit: ^0.18.0  
  latlong2: ^0.9.1  # Pastikan untuk menambahkan latlong2 jika belum ada
  fluttertoast: ^8.0.9
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  camera: ^0.9.4+5
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  form_field_validator: ^1.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/presensi.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
