// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPmdNAbZOjk8UKHHe3OXUWYwtMxolVvMw',
    appId: '1:1024392596116:web:21683c31e2c579c7c28281',
    messagingSenderId: '1024392596116',
    projectId: 'kehadiran-b9593',
    authDomain: 'kehadiran-b9593.firebaseapp.com',
    storageBucket: 'kehadiran-b9593.appspot.com',
    measurementId: 'G-L9R8RVRB4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv-VctnBTsbCDHJwFKuDlgV_zP0KgEXr0',
    appId: '1:1024392596116:android:b9f66eb2b50b15e4c28281',
    messagingSenderId: '1024392596116',
    projectId: 'kehadiran-b9593',
    storageBucket: 'kehadiran-b9593.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3x6-2OiYW9tT8v39_c9tIogxCDrB6BVw',
    appId: '1:1024392596116:ios:6ac770356d9dc474c28281',
    messagingSenderId: '1024392596116',
    projectId: 'kehadiran-b9593',
    storageBucket: 'kehadiran-b9593.appspot.com',
    iosBundleId: 'com.example.presensiApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPmdNAbZOjk8UKHHe3OXUWYwtMxolVvMw',
    appId: '1:1024392596116:web:7c7a75914fbf6350c28281',
    messagingSenderId: '1024392596116',
    projectId: 'kehadiran-b9593',
    authDomain: 'kehadiran-b9593.firebaseapp.com',
    storageBucket: 'kehadiran-b9593.appspot.com',
    measurementId: 'G-K987RQR562',
  );
}
